<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { calculateAnalysis } from './analysis/localAnalysis'
import { exportBackup, importBackup, workoutDb } from './db/database'
import { importWorkoutFile } from './services/importService'
import { requestTrainingPlan } from './services/aiService'
import { useI18n, type Locale } from './i18n'
import type { TrainingPlanDay, UserConfig, Workout } from './types/workout'

const { locale, t, setLocale, formatTime } = useI18n()
const workouts = ref<Workout[]>([]), plan = ref<TrainingPlanDay[]>([]), message = ref(''), loading = ref(false), consent = ref(false), search = ref('')
const backendStatus = ref<'checking' | 'online' | 'offline'>('checking'), backendVersion = ref('–'), backendCheckedAt = ref('')
const config = ref<UserConfig>({ name:'Athlet', trainingFocus:'base_endurance', preferredTrainingDays:['monday','wednesday','friday'], hrZones:{ z1:[90,106], z2:[107,124], z3:[125,142], z4:[143,160], z5:[161,179] }, thresholds:{ lthr:160, hr_max:186 } })
const analysis = computed(() => calculateAnalysis(workouts.value, config.value))
const filteredWorkouts = computed(() => workouts.value.filter(workout => `${workout.name} ${workout.sport} ${workout.date}`.toLowerCase().includes(search.value.toLowerCase())).sort((a,b) => b.date.localeCompare(a.date)))
onMounted(async () => { workouts.value = await workoutDb.list(); const stored = await workoutDb.getConfig(); if (stored) config.value = stored; await checkBackend() })
async function checkBackend() { try { const apiUrl = import.meta.env.VITE_AI_API_URL || '/api'; const response = await fetch(`${apiUrl.replace(/\/api\/?$/, '')}/health`, { signal:AbortSignal.timeout(8000) }); if (!response.ok) throw new Error(); const health = await response.json() as { status?:string; version?:string }; backendStatus.value = health.status === 'ok' ? 'online' : 'offline'; backendVersion.value = health.version || t.value.backendUnknown } catch { backendStatus.value='offline'; backendVersion.value='–' } finally { backendCheckedAt.value = formatTime(new Date()) } }
async function importFiles(event: Event) { const files = Array.from((event.target as HTMLInputElement).files || []); let imported=0; for (const file of files) { try { await importWorkoutFile(file); imported++ } catch { message.value=t.value.importFailed } }; workouts.value=await workoutDb.list(); if (imported) message.value=t.value.importSuccess(imported) }
async function createPlan() { if (!consent.value) { message.value=t.value.consent; return }; loading.value=true; try { plan.value=await requestTrainingPlan(workouts.value, config.value); await workoutDb.savePlan(plan.value); message.value=t.value.planSaved } catch { message.value=t.value.aiFailed } finally { loading.value=false } }
async function saveConfig() { await workoutDb.saveConfig(config.value); message.value=t.value.configSaved }
async function downloadBackup() { const blob=new Blob([JSON.stringify(await exportBackup(),null,2)],{type:'application/json'}); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=`lauftrainer-backup-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(link.href); message.value=t.value.backupExported }
async function restoreBackup(event: Event) { const file=(event.target as HTMLInputElement).files?.[0]; if (!file) return; try { await importBackup(JSON.parse(await file.text())); workouts.value=await workoutDb.list(); message.value=t.value.backupRestored } catch { message.value=t.value.backupFailed } }
async function clearData() { if (!window.confirm(t.value.confirmDelete)) return; await workoutDb.deleteAll(); workouts.value=[]; plan.value=[]; message.value=t.value.dataDeleted }
</script>

<template>
  <main class="shell"><header><div><p class="eyebrow">{{ t.coach }}</p><h1>LaufTrainer</h1></div><div class="header-actions"><label class="language-switcher"><span>{{ t.language }}</span><select :value="locale" @change="setLocale(($event.target as HTMLSelectElement).value as Locale)"><option value="de">{{ t.german }}</option><option value="en">{{ t.english }}</option></select></label><span class="badge">{{ t.offlineReady }}</span></div></header>
    <section class="hero"><div><h2>{{ t.heroTitle }}</h2><p>{{ t.heroText }}</p></div><label class="button primary">{{ t.importFiles }}<input type="file" multiple accept=".csv,.json,.tcx" @change="importFiles"></label></section>
    <p v-if="message" class="notice">{{ message }}</p><section class="stats"><article class="card"><span>{{ t.workouts }}</span><strong class="metric">{{ workouts.length }}</strong></article><article class="card"><span>{{ t.totalDistance }}</span><strong class="metric">{{ analysis.totalDistanceKm.toFixed(1) }} km</strong></article><article class="card"><span>{{ t.trainingTime }}</span><strong class="metric">{{ Math.round(analysis.totalDurationMinutes/60) }} h</strong></article></section>
    <section class="grid"><article class="card"><p class="eyebrow">{{ t.history }}</p><input v-model="search" class="search" :placeholder="t.search"><ul class="workouts"><li v-for="workout in filteredWorkouts.slice(0,12)" :key="workout.id"><strong>{{ workout.date }}</strong><span>{{ workout.sport }} · {{ Math.round(workout.durationSeconds/60) }} min · {{ workout.distanceKm?.toFixed(1) || '–' }} km</span></li><li v-if="!filteredWorkouts.length">{{ t.noWorkouts }}</li></ul></article>
      <article class="card"><p class="eyebrow">{{ t.weekOverview }}</p><div class="weeks"><div v-for="week in analysis.weekly.slice(-8).reverse()" :key="week.weekStart"><strong>{{ week.weekStart }}</strong><span>{{ week.distanceKm.toFixed(1) }} km · {{ week.workoutCount }} {{ t.units }}</span><i :style="{width:`${Math.min(100,week.distanceKm*3)}%`}"></i></div><p v-if="!analysis.weekly.length">{{ t.noWeeks }}</p></div></article></section>
    <section class="card"><p class="eyebrow">{{ t.settings }}</p><div class="settings"><label>{{ t.name }}<input v-model="config.name" @change="saveConfig"></label><label>{{ t.lthr }}<input v-model.number="config.thresholds.lthr" type="number" @change="saveConfig"></label><button class="button secondary" @click="downloadBackup">{{ t.exportBackup }}</button><label class="button secondary">{{ t.importBackup }}<input type="file" accept=".json" @change="restoreBackup"></label><button class="text-button" @click="clearData">{{ t.deleteData }}</button></div></section>
    <section class="card"><p class="eyebrow">{{ t.aiPlan }}</p><p>{{ t.aiDescription }}</p><label class="consent"><input v-model="consent" type="checkbox"> {{ t.consent }}</label><button class="button primary full" :disabled="loading || !workouts.length" @click="createPlan">{{ loading ? t.creatingPlan : t.createPlan }}</button><div v-if="plan.length" class="plan"><div v-for="day in plan" :key="day.day"><strong>{{ day.day }}</strong><span>{{ day.description }} · {{ day.total_duration_minutes }} min</span></div></div></section>
    <footer><span>{{ t.localUpload }}</span><button class="backend-status" :class="backendStatus" :title="t.checkBackend" @click="checkBackend"><i></i><span v-if="backendStatus==='checking'">{{ t.checking }}</span><span v-else-if="backendStatus==='online'">{{ t.online }} · v{{ backendVersion }}</span><span v-else>{{ t.offline }}</span><small v-if="backendCheckedAt">{{ backendCheckedAt }}</small></button></footer>
  </main>
</template>
