import { computed, ref } from 'vue'

export type Locale = 'de' | 'en'
const translations = {
  de: { connectPolar:'Mit Polar verbinden', syncPolar:'Neue Polar-Trainings laden', syncingPolar:'Polar-Trainings werden geladen …', polarConnected:'Polar verbunden', coach:'LOKALER TRAININGSCOACH', offlineReady:'Offline bereit', heroTitle:'Deine Daten bleiben auf deinem Gerät.', heroText:'Importiere Polar-Exporte, analysiere deine Historie lokal und fordere bei Bedarf einen KI-Plan an.', importFiles:'Dateien importieren', workouts:'Workouts', totalDistance:'Distanz gesamt', trainingTime:'Trainingszeit', history:'TRAININGSHISTORIE', search:'Workouts suchen …', noWorkouts:'Noch keine passenden Workouts.', weekOverview:'WOCHENÜBERSICHT', noWeeks:'Nach dem Import erscheinen hier deine Wochenwerte.', units:'Einheiten', settings:'DATEN UND EINSTELLUNGEN', name:'Name', lthr:'LTHR', exportBackup:'Backup exportieren', importBackup:'Backup importieren', deleteData:'Lokale Daten löschen', aiPlan:'KI-TRAININGSPLAN', aiDescription:'Nur die verdichtete Zusammenfassung wird nach Zustimmung an das KI-Backend übertragen.', consent:'Ich stimme diesem KI-Aufruf zu.', createPlan:'Plan erstellen', creatingPlan:'Plan wird erstellt …', localUpload:'IndexedDB · kein automatischer Upload', checkBackend:'Backend-Status erneut prüfen', checking:'Backend wird geprüft …', online:'Backend online', offline:'Backend offline', language:'Sprache', german:'Deutsch', english:'English', backendUnknown:'unbekannt', importSuccess:(count:number)=>`${count} Datei(en) lokal verarbeitet.`, importFailed:'Import fehlgeschlagen.', planSaved:'Trainingsplan lokal gespeichert.', aiFailed:'KI-Aufruf fehlgeschlagen.', configSaved:'Einstellungen lokal gespeichert.', backupExported:'Backup exportiert.', backupRestored:'Backup wiederhergestellt.', backupFailed:'Backup konnte nicht gelesen werden.', confirmDelete:'Alle lokalen Trainingsdaten löschen?', dataDeleted:'Lokale Trainingsdaten gelöscht.' },
  en: { connectPolar:'Connect Polar', syncPolar:'Load new Polar workouts', syncingPolar:'Loading Polar workouts …', polarConnected:'Polar connected', coach:'LOCAL TRAINING COACH', offlineReady:'Offline ready', heroTitle:'Your data stays on your device.', heroText:'Import Polar exports, analyze your history locally and request an AI plan when needed.', importFiles:'Import files', workouts:'Workouts', totalDistance:'Total distance', trainingTime:'Training time', history:'TRAINING HISTORY', search:'Search workouts …', noWorkouts:'No matching workouts yet.', weekOverview:'WEEKLY OVERVIEW', noWeeks:'Your weekly values will appear here after importing data.', units:'sessions', settings:'DATA AND SETTINGS', name:'Name', lthr:'LTHR', exportBackup:'Export backup', importBackup:'Import backup', deleteData:'Delete local data', aiPlan:'AI TRAINING PLAN', aiDescription:'Only the condensed summary is sent to the AI backend after your consent.', consent:'I consent to this AI request.', createPlan:'Create plan', creatingPlan:'Creating plan …', localUpload:'IndexedDB · no automatic upload', checkBackend:'Check backend status again', checking:'Checking backend …', online:'Backend online', offline:'Backend offline', language:'Language', german:'Deutsch', english:'English', backendUnknown:'unknown', importSuccess:(count:number)=>`${count} file(s) processed locally.`, importFailed:'Import failed.', planSaved:'Training plan saved locally.', aiFailed:'AI request failed.', configSaved:'Settings saved locally.', backupExported:'Backup exported.', backupRestored:'Backup restored.', backupFailed:'Backup could not be read.', confirmDelete:'Delete all local training data?', dataDeleted:'Local training data deleted.' }
} as const

const stored = localStorage.getItem('lauftrainer-locale') as Locale | null
const locale = ref<Locale>(stored === 'en' || (!stored && navigator.language.toLowerCase().startsWith('en')) ? 'en' : 'de')
export function useI18n() { const t = computed(() => translations[locale.value]); const setLocale = (value: Locale) => { locale.value=value; localStorage.setItem('lauftrainer-locale',value) }; const formatTime=(date:Date)=>date.toLocaleTimeString(locale.value==='de'?'de-DE':'en-US',{hour:'2-digit',minute:'2-digit'}); return { locale, t, setLocale, formatTime } }
