<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from '../i18n'
import type { TrainingPlanDay, UserConfig, Workout } from '../types/workout'
const props = defineProps<{ workouts: Workout[]; plan: TrainingPlanDay[]; config: UserConfig; analysis: { totalDistanceKm: number; totalDurationMinutes: number; weekly: Array<{ weekStart: string; distanceKm: number; workoutCount: number }> }; search: string; message: string; loading: boolean; consent: boolean; connectorLoading: boolean; syncConnectors: () => void; importFiles: (event: Event) => void; createPlan: () => void }>()
const emit = defineEmits<{ 'update:search': [value: string]; 'update:consent': [value: boolean] }>()
const { t } = useI18n()
const filteredWorkouts = computed(() => props.workouts.filter(workout => `${workout.name} ${workout.sport} ${workout.date}`.toLowerCase().includes(props.search.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date)))
</script>
<template>
  <div class="page-heading"><h1>{{ t.greeting }}</h1><label class="button primary">{{ t.importFiles }}<input type="file" multiple accept=".csv,.json,.tcx" @change="importFiles"></label></div>
  <section class="hero"><div><h2>{{ t.heroTitle }}</h2><p>{{ t.heroText }}</p></div><span class="hero-orb">◌</span></section>
  <p v-if="message" class="notice">{{ message }}</p>
  <section class="stats"><article class="card"><span>{{ t.workouts }}</span><strong class="metric">{{ workouts.length }}</strong></article><article class="card"><span>{{ t.totalDistance }}</span><strong class="metric">{{ analysis.totalDistanceKm.toFixed(1) }} km</strong></article><article class="card"><span>{{ t.trainingTime }}</span><strong class="metric">{{ Math.round(analysis.totalDurationMinutes / 60) }} h</strong></article></section>
  <section class="grid"><article class="card"><p class="eyebrow">{{ t.history }}</p><input :value="search" class="search" :placeholder="t.search" @input="emit('update:search', ($event.target as HTMLInputElement).value)"><ul class="workouts"><li v-for="workout in filteredWorkouts.slice(0, 12)" :key="workout.id"><strong>{{ workout.date }}</strong><span>{{ workout.sport }} · {{ Math.round(workout.durationSeconds / 60) }} min · {{ workout.distanceKm?.toFixed(1) || '–' }} km</span></li><li v-if="!filteredWorkouts.length">{{ t.noWorkouts }}</li></ul></article><article class="card"><p class="eyebrow">{{ t.weekOverview }}</p><div class="weeks"><div v-for="week in analysis.weekly.slice(-8).reverse()" :key="week.weekStart"><strong>{{ week.weekStart }}</strong><span>{{ week.distanceKm.toFixed(1) }} km · {{ week.workoutCount }} {{ t.units }}</span><i :style="{ width: `${Math.min(100, week.distanceKm * 3)}%` }"></i></div><p v-if="!analysis.weekly.length">{{ t.noWeeks }}</p></div></article></section>
  <section class="card"><div class="card-heading"><div><p class="eyebrow">{{ t.connectors }}</p><h3>{{ t.syncAllConnectors }}</h3></div><span class="connection-dot"></span></div><button class="button primary" :disabled="connectorLoading" @click="syncConnectors">{{ connectorLoading ? t.syncingConnectors : t.syncConnectors }}</button></section>
  <section class="card"><p class="eyebrow">{{ t.aiPlan }}</p><p>{{ t.aiDescription }}</p><label class="consent"><input :checked="consent" type="checkbox" @change="emit('update:consent', ($event.target as HTMLInputElement).checked)"> {{ t.consent }}</label><button class="button primary full" :disabled="loading || !workouts.length" @click="createPlan">{{ loading ? t.creatingPlan : t.createPlan }}</button><div v-if="plan.length" class="plan"><div v-for="day in plan" :key="day.day"><strong>{{ day.day }}</strong><span>{{ day.description }} · {{ day.total_duration_minutes }} min</span></div></div></section>
</template>
